server:
  port: 8123
  servlet:
    context-path: /api
    # session 配置
    session:
      cookie:
        max-age: 2592000 # session 30 天过期


spring:
  application:
    name: lu-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  # Rdis配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: root@123456
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
  session:
    store-type: redis
    timeout: 2592000  # session 30 天过期
    # 空间图片分表
  shardingsphere:
    datasource:
      names: lu_picture
      lu_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lu_picture
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: lu_picture.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.lu.lupicturebackend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    #  日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete #逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0
    enable-sql-runner: true  # 开启sql运行器

knife4j:
  enable: true
  openapi:
    title: 接口文档
    email: xiaoymin@foxmail.com
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.lu.lupicturebackend.controller

aliyunAi:
  apikey: ${aliyunAi.apikey}



